### ISSUE TITLE
Previous answers in textbox after "taking the L"

### ISSUE THREAD

**Issue by sam-30** [dancameron/well-dave#2]
**Describe the bug**
I guessed wrong on the movie Sick, but had the ending of the limerick correct.  I got 3 hints and clicked the "Take the L" button.  I then clicked the "next" button when on the movie poster page.  The next movie page had the textbox values from the Sick movie populated.

**To Reproduce**
1. Get 3 hints
2. Take the L
3. Click "Next" 
4. Observe textboxes with previous movie values

**Expected behavior**
I expected the textbox values to be blank for a new movie

**Comment by dancameron** [comment]
Thank you for submitting this ticket. That's pretty awesome. I was afraid no one would, even if they found one, haha.

Thanks for pointing this out! It's fixed.

**Comment by dancameron** [comment]
Thank you! It caught me just at the right time between projects and was especially fun to build.
