### ISSUE TITLE
Info for tt1649418 is Wrong

### ISSUE THREAD

**Issue by prollup** [dancameron/well-dave#3]
**What movie**

**What information is incorrect**

**Additional context**
I just noticed that the last hint is covered by the x Button.

![Screenshot_20230329-085359](https://user-images.githubusercontent.com/18155556/228543071-24f16454-07e6-4041-b93c-d162183c2de5.png)

**Comment by dancameron** [comment]
Thank you for this. I totally forgot about it after seeing it on my phone away from the computer. All fixed and deployed.

Thanks for playing!
